#!/usr/bin/env bash
# configures a server to listening on port 80 of all servers active IPv4 IPs

ls -sf /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
