#!/usr/bin/env bash

#Permission
chmod 644 /etc/nginx/nginx.conf

# Run Nginx as nginx
sudo sed -i 's/*user www-data/user nginx' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
# restart nginx
sudo -u nginx service nginx restart
